# Generated by Django 5.1.5 on 2025-03-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RicettarioX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedrecipe',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
