# Generated by Django 5.1.5 on 2025-03-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RicettarioX', '0002_generatedrecipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
    ]
