# Generated by Django 5.1.5 on 2025-03-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RicettarioX', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='generatedingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
